### ISSUE TITLE
How to access the raw sensor pixel values

### ISSUE THREAD

**Issue by SteveRowl** [hurlbertvisionlab/LibRawWrapper#1]
Thanks 'jantheman' for your comment on Libraw.org forum re issue 2711. I appreciate it.

I have downloaded your 'LibRawWrapper' via NuGet into VS2019 running VB.NET. Changed compile option to X64. Runs in debug mode just fine.

I am testing with a Canon 600D CR2 file. File Opens and Unpacks without error. The LibRawProcessor.RawData.BufferFormat has a value of 1. (Short) and I can see the LibRawProcessor.RawData.Buffer value is presumably a pointer to the memory location of the raw data.

However, I am not understanding how to get the raw sensor pixel values into an array.

I have tried this VB.NET code:

Array sized to the height and width = CType(Marshal.PtrToStructure(CType(LibRawProcessor.RawData.Buffer, IntPtr), GetType(Short())), Short())

If you are able to advise on the C# code to do this, I would be able to rewrite it into VB.NET.

Thanks. SteveR.

**Comment by jantheman** [comment]
Hi Steve!

No problem, yes the Buffer is a pointer to an unmanaged memory array. It depends exactly on what you want to do with the data, but if you just want to copy it into a managed Short array, you first need to declare your array of the appropriate length and then you can use `Marshal.Copy` from `System.Runtime.InteropServices`, see https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.copy?view=net-6.0#system-runtime-interopservices-marshal-copy(system-intptr-system-int16()-system-int32-system-int32)

```vb
Imports System.Runtime.InteropServices

...

Dim data(width * height) As Short
Marshal.Copy(libRawProcessor.RawData.Buffer, data, 0, data.Length)
```

(assuming width is aligned)

**Comment by SteveRowl** [comment]
Fantastic! It works.

I have been struggling with LibRaw for some time and not being a C or C++ programmer, it is not easy.

Do I assume that your wrapper needs to be recompiled from your/LibRaw source code each time the LibRaw library itself is updated? 
If so, does that also mean that when the LibRaw library is updated for new DSLR cameras, your wrapper also needs to be recompiled?

Many thanks.

SteveR

**Comment by jantheman** [comment]
That is correct. I wanted it to be a single file, so the libraw library is compiled into the wrapper. It might be possible to setup some process that does that automatically whenever new version of libraw is released, however, note that the releases do not happen very often. Last one was in 2020 and I needed to use some of the cameras/features only present in the later drops. So even though it has been almost a year now, the wrapper you are using now in fact contains a not-yet-released libraw version.

**Comment by SteveRowl** [comment]
OK. Understand.

I am working with another developer in the USA who wrote a popular astronomy photometry program many years ago which is widely used by amateur astronomers such as myself. I am a retired VB6, VB.NET programmer, SQL developer. We are completely rewriting it for several reasons.

This wrapper would be invaluable to us because many amateurs use a wide range of DSLR cameras.

I go away for a 3 week overseas holiday within the week so I won't have much time before I go to communicate further, but I certainly will when I return. In the mean time I will explore what other camera data your wrapper exposes.

BTW, if I may ask, what time zone are you in? Do you have a public facing website?

Regards

**Comment by jantheman** [comment]
You can see the release notes here: https://www.libraw.org/blog. So based on the dates, the current wrapper build uses the 202101 snapshot.
